import { Product } from "./types";

export const catalog: Product[] = [
  // === SOFAS & SECTIONALS ===
  {
    id: "sf-001",
    name: "Aldridge Chesterfield Sofa",
    category: "sofa",
    price: 1249,
    rating: 4.7,
    aesthetic_tags: ["dark-academia", "maximalist"],
    material_tags: ["velvet", "dark wood"],
    colors: ["#722F37", "#3B2314"],
    description: "Tufted burgundy velvet Chesterfield with rolled arms and dark walnut legs.",
    image_url: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600",
    dimensions: { w: 88, d: 36, h: 32 },
    assembly_required: false,
  },
  {
    id: "sf-002",
    name: "Mori Low-Profile Sofa",
    category: "sofa",
    price: 899,
    rating: 4.5,
    aesthetic_tags: ["japandi", "minimalist", "scandinavian"],
    material_tags: ["linen", "light wood"],
    colors: ["#D4C5A9", "#C8B896"],
    description: "Clean-lined low sofa in oatmeal linen with natural ash frame.",
    image_url: "https://images.unsplash.com/photo-1567016432779-094069958ea5?w=600",
    dimensions: { w: 82, d: 34, h: 28 },
    assembly_required: false,
  },
  {
    id: "sf-003",
    name: "Catalina Slipcovered Sofa",
    category: "sofa",
    price: 1079,
    rating: 4.6,
    aesthetic_tags: ["coastal-grandmother", "cottagecore"],
    material_tags: ["linen", "cotton"],
    colors: ["#F5F0E8", "#E8DDD0"],
    description: "Relaxed slipcovered sofa in washed white linen. Effortlessly coastal.",
    image_url: "https://images.unsplash.com/photo-1550254478-ead40cc54513?w=600",
    dimensions: { w: 86, d: 38, h: 33 },
    assembly_required: false,
  },
  {
    id: "sf-004",
    name: "Vesper Velvet Sectional",
    category: "sofa",
    price: 1899,
    rating: 4.8,
    aesthetic_tags: ["maximalist", "bohemian"],
    material_tags: ["velvet", "brass"],
    colors: ["#2D4A2D", "#C4A35A"],
    description: "Emerald green velvet L-sectional with brass cap feet.",
    image_url: "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=600",
    dimensions: { w: 110, d: 85, h: 32 },
    assembly_required: true,
  },
  {
    id: "sf-005",
    name: "Henning Leather Sofa",
    category: "sofa",
    price: 1549,
    rating: 4.6,
    aesthetic_tags: ["mid-century", "industrial"],
    material_tags: ["leather", "metal"],
    colors: ["#8B4513", "#2C2C2C"],
    description: "Cognac top-grain leather sofa on black steel hairpin legs.",
    image_url: "https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=600",
    dimensions: { w: 84, d: 35, h: 31 },
    assembly_required: false,
  },

  // === ACCENT CHAIRS ===
  {
    id: "ac-001",
    name: "Pemberton Wingback Chair",
    category: "accent-chair",
    price: 649,
    rating: 4.5,
    aesthetic_tags: ["dark-academia", "maximalist"],
    material_tags: ["velvet", "dark wood"],
    colors: ["#2D4A2D", "#3B2314"],
    description: "Forest green velvet wingback with deep button tufting and carved mahogany legs.",
    image_url: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600",
    dimensions: { w: 32, d: 34, h: 42 },
    assembly_required: false,
  },
  {
    id: "ac-002",
    name: "Kyoto Lounge Chair",
    category: "accent-chair",
    price: 479,
    rating: 4.4,
    aesthetic_tags: ["japandi", "scandinavian", "minimalist"],
    material_tags: ["light wood", "cotton"],
    colors: ["#D4C5A9", "#E8DCC8"],
    description: "Low-slung oak lounge chair with woven cotton seat in warm sand.",
    image_url: "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=600",
    dimensions: { w: 28, d: 30, h: 30 },
    assembly_required: true,
  },
  {
    id: "ac-003",
    name: "Nantucket Wicker Armchair",
    category: "accent-chair",
    price: 389,
    rating: 4.3,
    aesthetic_tags: ["coastal-grandmother", "cottagecore", "bohemian"],
    material_tags: ["rattan", "wicker", "cotton"],
    colors: ["#C4A35A", "#F5F0E8"],
    description: "Hand-woven rattan armchair with cream linen cushion.",
    image_url: "https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=600",
    dimensions: { w: 30, d: 28, h: 34 },
    assembly_required: false,
  },
  {
    id: "ac-004",
    name: "Eames-Style Shell Chair",
    category: "accent-chair",
    price: 299,
    rating: 4.6,
    aesthetic_tags: ["mid-century", "scandinavian"],
    material_tags: ["molded plastic", "wood"],
    colors: ["#F5F0E8", "#C8A96E"],
    description: "Molded shell chair in warm white with walnut dowel legs.",
    image_url: "https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=600",
    dimensions: { w: 25, d: 24, h: 32 },
    assembly_required: true,
  },
  {
    id: "ac-005",
    name: "Foundry Metal Accent Chair",
    category: "accent-chair",
    price: 429,
    rating: 4.2,
    aesthetic_tags: ["industrial", "mid-century"],
    material_tags: ["metal", "leather"],
    colors: ["#2C2C2C", "#8B4513"],
    description: "Distressed leather sling chair on matte black iron frame.",
    image_url: "https://images.unsplash.com/photo-1519947486511-46149fa0a254?w=600",
    dimensions: { w: 26, d: 30, h: 33 },
    assembly_required: true,
  },

  // === COFFEE TABLES ===
  {
    id: "ct-001",
    name: "Ashford Library Table",
    category: "coffee-table",
    price: 549,
    rating: 4.5,
    aesthetic_tags: ["dark-academia", "maximalist"],
    material_tags: ["dark wood", "brass"],
    colors: ["#3B2314", "#C4A35A"],
    description: "Dark walnut coffee table with brass corner accents and a lower shelf for books.",
    image_url: "https://images.unsplash.com/photo-1532372576444-dda954194ad0?w=600",
    dimensions: { w: 48, d: 24, h: 18 },
    assembly_required: true,
  },
  {
    id: "ct-002",
    name: "Zen Stone Coffee Table",
    category: "coffee-table",
    price: 429,
    rating: 4.7,
    aesthetic_tags: ["japandi", "minimalist"],
    material_tags: ["light wood", "stone"],
    colors: ["#D4C5A9", "#9C9A8E"],
    description: "Oval white oak table with a natural stone inset.",
    image_url: "https://images.unsplash.com/photo-1533090481720-856c6e3c1fdc?w=600",
    dimensions: { w: 42, d: 22, h: 14 },
    assembly_required: false,
  },
  {
    id: "ct-003",
    name: "Driftwood Round Table",
    category: "coffee-table",
    price: 379,
    rating: 4.4,
    aesthetic_tags: ["coastal-grandmother", "bohemian"],
    material_tags: ["reclaimed wood", "light wood"],
    colors: ["#C4A35A", "#E8DDD0"],
    description: "Round reclaimed driftwood coffee table with whitewashed finish.",
    image_url: "https://images.unsplash.com/photo-1611486212557-88be5ff6f941?w=600",
    dimensions: { w: 36, d: 36, h: 16 },
    assembly_required: false,
  },
  {
    id: "ct-004",
    name: "Helsinki Nesting Tables",
    category: "coffee-table",
    price: 349,
    rating: 4.5,
    aesthetic_tags: ["scandinavian", "mid-century", "minimalist"],
    material_tags: ["light wood", "metal"],
    colors: ["#E8DCC8", "#2C2C2C"],
    description: "Set of 3 birch nesting tables with slim black metal legs.",
    image_url: "https://images.unsplash.com/photo-1499933374294-4584851497cc?w=600",
    dimensions: { w: 40, d: 20, h: 17 },
    assembly_required: true,
  },
  {
    id: "ct-005",
    name: "Ironworks Cart Table",
    category: "coffee-table",
    price: 469,
    rating: 4.3,
    aesthetic_tags: ["industrial", "mid-century"],
    material_tags: ["metal", "reclaimed wood"],
    colors: ["#2C2C2C", "#8B6914"],
    description: "Rolling cart-style table with iron frame and reclaimed pine top.",
    image_url: "https://images.unsplash.com/photo-1530018607912-eff2daa1bac4?w=600",
    dimensions: { w: 44, d: 22, h: 18 },
    assembly_required: true,
  },

  // === BOOKSHELVES & STORAGE ===
  {
    id: "bs-001",
    name: "Oxford Tall Bookcase",
    category: "bookshelf",
    price: 799,
    rating: 4.8,
    aesthetic_tags: ["dark-academia", "maximalist"],
    material_tags: ["dark wood", "brass"],
    colors: ["#3B2314", "#C4A35A"],
    description: "Tall mahogany bookcase with brass ladder rail and 6 adjustable shelves.",
    image_url: "https://images.unsplash.com/photo-1594620302200-9a762244a156?w=600",
    dimensions: { w: 36, d: 14, h: 84 },
    assembly_required: true,
  },
  {
    id: "bs-002",
    name: "Muji-Style Open Shelf",
    category: "bookshelf",
    price: 349,
    rating: 4.4,
    aesthetic_tags: ["japandi", "minimalist", "scandinavian"],
    material_tags: ["light wood"],
    colors: ["#D4C5A9"],
    description: "5-tier open shelf in natural ash. Clean grid lines, no back panel.",
    image_url: "https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=600",
    dimensions: { w: 32, d: 12, h: 72 },
    assembly_required: true,
  },
  {
    id: "bs-003",
    name: "Farmhouse Hutch",
    category: "bookshelf",
    price: 679,
    rating: 4.5,
    aesthetic_tags: ["cottagecore", "coastal-grandmother"],
    material_tags: ["reclaimed wood", "glass"],
    colors: ["#F5F0E8", "#C4A35A"],
    description: "Distressed white hutch with glass doors and reclaimed pine shelves.",
    image_url: "https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=600",
    dimensions: { w: 40, d: 16, h: 78 },
    assembly_required: true,
  },
  {
    id: "bs-004",
    name: "Pipe & Plank Wall Shelf",
    category: "bookshelf",
    price: 279,
    rating: 4.3,
    aesthetic_tags: ["industrial", "bohemian"],
    material_tags: ["metal", "reclaimed wood"],
    colors: ["#2C2C2C", "#8B6914"],
    description: "Wall-mounted industrial shelving with iron pipe brackets and reclaimed oak planks.",
    image_url: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600",
    dimensions: { w: 48, d: 10, h: 36 },
    assembly_required: true,
  },

  // === FLOOR LAMPS & LIGHTING ===
  {
    id: "fl-001",
    name: "Kensington Brass Floor Lamp",
    category: "floor-lamp",
    price: 289,
    rating: 4.6,
    aesthetic_tags: ["dark-academia", "maximalist", "mid-century"],
    material_tags: ["brass", "glass"],
    colors: ["#C4A35A", "#F5F0E8"],
    description: "Adjustable brass floor lamp with frosted glass globe shade.",
    image_url: "https://images.unsplash.com/photo-1507473885765-e6ed057ab3fe?w=600",
    dimensions: { w: 12, d: 12, h: 62 },
    assembly_required: true,
  },
  {
    id: "fl-002",
    name: "Akari Paper Lantern Lamp",
    category: "floor-lamp",
    price: 219,
    rating: 4.5,
    aesthetic_tags: ["japandi", "minimalist", "scandinavian"],
    material_tags: ["paper", "bamboo"],
    colors: ["#F5F0E8", "#D4C5A9"],
    description: "Rice paper floor lantern on slim bamboo tripod. Warm diffused glow.",
    image_url: "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=600",
    dimensions: { w: 14, d: 14, h: 58 },
    assembly_required: true,
  },
  {
    id: "fl-003",
    name: "Seaside Rope Floor Lamp",
    category: "floor-lamp",
    price: 179,
    rating: 4.2,
    aesthetic_tags: ["coastal-grandmother", "cottagecore"],
    material_tags: ["rope", "linen", "light wood"],
    colors: ["#C4A35A", "#F5F0E8"],
    description: "Driftwood-style base wrapped in nautical rope with natural linen shade.",
    image_url: "https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?w=600",
    dimensions: { w: 16, d: 16, h: 60 },
    assembly_required: true,
  },
  {
    id: "fl-004",
    name: "Arc Overreach Floor Lamp",
    category: "floor-lamp",
    price: 329,
    rating: 4.7,
    aesthetic_tags: ["mid-century", "minimalist"],
    material_tags: ["metal", "marble"],
    colors: ["#2C2C2C", "#F5F0E8"],
    description: "Chrome arc lamp with white marble base and adjustable drum shade.",
    image_url: "https://images.unsplash.com/photo-1543198126-a8ad8e47fb22?w=600",
    dimensions: { w: 40, d: 16, h: 76 },
    assembly_required: true,
  },
  {
    id: "fl-005",
    name: "Edison Cage Floor Lamp",
    category: "floor-lamp",
    price: 199,
    rating: 4.4,
    aesthetic_tags: ["industrial", "bohemian"],
    material_tags: ["metal", "iron"],
    colors: ["#2C2C2C", "#C4823A"],
    description: "Matte black iron tripod lamp with exposed Edison bulb and cage shade.",
    image_url: "https://images.unsplash.com/photo-1534105615256-13940a56ff44?w=600",
    dimensions: { w: 18, d: 18, h: 64 },
    assembly_required: true,
  },

  // === AREA RUGS ===
  {
    id: "ar-001",
    name: "Persian Revival Rug",
    category: "area-rug",
    price: 449,
    rating: 4.6,
    aesthetic_tags: ["dark-academia", "maximalist", "bohemian"],
    material_tags: ["wool", "cotton"],
    colors: ["#722F37", "#2D4A2D", "#C4A35A"],
    description: "Rich burgundy and forest green Persian-pattern rug in hand-knotted wool.",
    image_url: "https://images.unsplash.com/photo-1600166898405-da9535204843?w=600",
    dimensions: { w: 96, d: 60, h: 0.5 },
    assembly_required: false,
  },
  {
    id: "ar-002",
    name: "Wabi-Sabi Jute Rug",
    category: "area-rug",
    price: 299,
    rating: 4.3,
    aesthetic_tags: ["japandi", "minimalist", "scandinavian"],
    material_tags: ["jute", "cotton"],
    colors: ["#D4C5A9", "#C8B896"],
    description: "Handwoven jute and cotton blend rug in natural tones. Imperfect texture.",
    image_url: "https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?w=600",
    dimensions: { w: 96, d: 60, h: 0.3 },
    assembly_required: false,
  },
  {
    id: "ar-003",
    name: "Cape Cod Striped Rug",
    category: "area-rug",
    price: 329,
    rating: 4.4,
    aesthetic_tags: ["coastal-grandmother", "cottagecore"],
    material_tags: ["cotton", "linen"],
    colors: ["#7BA7BC", "#F5F0E8"],
    description: "Blue and ivory striped flatweave rug. Machine washable cotton-linen blend.",
    image_url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=600",
    dimensions: { w: 96, d: 60, h: 0.2 },
    assembly_required: false,
  },
  {
    id: "ar-004",
    name: "Kilim Pattern Rug",
    category: "area-rug",
    price: 399,
    rating: 4.5,
    aesthetic_tags: ["bohemian", "maximalist", "mid-century"],
    material_tags: ["wool", "cotton"],
    colors: ["#C4823A", "#2D4A2D", "#722F37"],
    description: "Vibrant kilim-patterned rug in terracotta, green, and burgundy.",
    image_url: "https://images.unsplash.com/photo-1575414003552-1839e15ac23f?w=600",
    dimensions: { w: 96, d: 60, h: 0.4 },
    assembly_required: false,
  },
  {
    id: "ar-005",
    name: "Concrete Effect Rug",
    category: "area-rug",
    price: 279,
    rating: 4.2,
    aesthetic_tags: ["industrial", "minimalist"],
    material_tags: ["synthetic", "cotton"],
    colors: ["#9C9A8E", "#2C2C2C"],
    description: "Low-pile rug with concrete-wash effect in cool grays.",
    image_url: "https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=600",
    dimensions: { w: 96, d: 60, h: 0.2 },
    assembly_required: false,
  },

  // === SIDE TABLES ===
  {
    id: "st-001",
    name: "Antiquarian Side Table",
    category: "side-table",
    price: 249,
    rating: 4.4,
    aesthetic_tags: ["dark-academia", "maximalist"],
    material_tags: ["dark wood", "brass"],
    colors: ["#3B2314", "#C4A35A"],
    description: "Round dark walnut side table with brass gallery rim and turned legs.",
    image_url: "https://images.unsplash.com/photo-1499916078039-922301b0eb9b?w=600",
    dimensions: { w: 20, d: 20, h: 24 },
    assembly_required: false,
  },
  {
    id: "st-002",
    name: "Torii Side Table",
    category: "side-table",
    price: 189,
    rating: 4.5,
    aesthetic_tags: ["japandi", "minimalist", "scandinavian"],
    material_tags: ["light wood"],
    colors: ["#D4C5A9"],
    description: "Hinoki cypress C-table that slides over sofa arms. Grain is the decoration.",
    image_url: "https://images.unsplash.com/photo-1565791380713-1756b9a05343?w=600",
    dimensions: { w: 18, d: 14, h: 24 },
    assembly_required: false,
  },
  {
    id: "st-003",
    name: "Coral Bay Accent Table",
    category: "side-table",
    price: 159,
    rating: 4.3,
    aesthetic_tags: ["coastal-grandmother", "cottagecore"],
    material_tags: ["rattan", "glass"],
    colors: ["#C4A35A", "#F5F0E8"],
    description: "Rattan drum side table with glass top. Airy and beachy.",
    image_url: "https://images.unsplash.com/photo-1532372576444-dda954194ad0?w=600",
    dimensions: { w: 18, d: 18, h: 22 },
    assembly_required: false,
  },
  {
    id: "st-004",
    name: "Hairpin Leg Side Table",
    category: "side-table",
    price: 139,
    rating: 4.4,
    aesthetic_tags: ["mid-century", "industrial"],
    material_tags: ["walnut", "metal"],
    colors: ["#8B4513", "#2C2C2C"],
    description: "Walnut round top on black hairpin legs. Classic mid-century form.",
    image_url: "https://images.unsplash.com/photo-1530018607912-eff2daa1bac4?w=600",
    dimensions: { w: 16, d: 16, h: 22 },
    assembly_required: true,
  },

  // === BEDS & HEADBOARDS ===
  {
    id: "bd-001",
    name: "Stratford Upholstered Bed",
    category: "bed",
    price: 1399,
    rating: 4.7,
    aesthetic_tags: ["dark-academia", "maximalist"],
    material_tags: ["velvet", "dark wood"],
    colors: ["#2D4A2D", "#3B2314"],
    description: "Queen bed with tall tufted forest green velvet headboard and dark walnut frame.",
    image_url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=600",
    dimensions: { w: 65, d: 88, h: 56 },
    assembly_required: true,
  },
  {
    id: "bd-002",
    name: "Tatami Platform Bed",
    category: "bed",
    price: 849,
    rating: 4.6,
    aesthetic_tags: ["japandi", "minimalist"],
    material_tags: ["light wood"],
    colors: ["#D4C5A9", "#E8DCC8"],
    description: "Low platform bed in natural ash with slat headboard. Floor-hugging design.",
    image_url: "https://images.unsplash.com/photo-1617325247661-675ab4b64ae2?w=600",
    dimensions: { w: 63, d: 86, h: 28 },
    assembly_required: true,
  },
  {
    id: "bd-003",
    name: "Hampton Canopy Bed",
    category: "bed",
    price: 1199,
    rating: 4.5,
    aesthetic_tags: ["coastal-grandmother", "cottagecore"],
    material_tags: ["light wood", "linen"],
    colors: ["#F5F0E8", "#C4A35A"],
    description: "Whitewashed wood four-poster bed with flowing linen canopy drapes.",
    image_url: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=600",
    dimensions: { w: 65, d: 88, h: 82 },
    assembly_required: true,
  },
  {
    id: "bd-004",
    name: "Nelson Platform Bed",
    category: "bed",
    price: 999,
    rating: 4.6,
    aesthetic_tags: ["mid-century", "scandinavian"],
    material_tags: ["walnut", "metal"],
    colors: ["#8B4513", "#2C2C2C"],
    description: "Walnut platform bed with angled legs and floating nightstand wings.",
    image_url: "https://images.unsplash.com/photo-1588046130717-0eb0c9a3ba15?w=600",
    dimensions: { w: 66, d: 87, h: 36 },
    assembly_required: true,
  },

  // === DECORATIVE / EXTRAS ===
  {
    id: "dc-001",
    name: "Botanical Print Set",
    category: "wall-art",
    price: 129,
    rating: 4.4,
    aesthetic_tags: ["dark-academia", "cottagecore"],
    material_tags: ["paper", "wood"],
    colors: ["#2D4A2D", "#3B2314", "#F5F0E8"],
    description: "Set of 4 vintage botanical prints in dark wood frames.",
    image_url: "https://images.unsplash.com/photo-1513519245088-0e12902e35ca?w=600",
    dimensions: { w: 48, d: 1, h: 36 },
    assembly_required: false,
  },
  {
    id: "dc-002",
    name: "Woven Macrame Wall Hanging",
    category: "wall-art",
    price: 89,
    rating: 4.3,
    aesthetic_tags: ["bohemian", "coastal-grandmother", "cottagecore"],
    material_tags: ["cotton", "rope"],
    colors: ["#F5F0E8", "#D4C5A9"],
    description: "Large hand-knotted macrame wall hanging in natural cotton.",
    image_url: "https://images.unsplash.com/photo-1622372738946-62e02505feb3?w=600",
    dimensions: { w: 36, d: 1, h: 48 },
    assembly_required: false,
  },
  {
    id: "dc-003",
    name: "Brass Desk Globe",
    category: "decor",
    price: 149,
    rating: 4.6,
    aesthetic_tags: ["dark-academia", "maximalist"],
    material_tags: ["brass", "paper"],
    colors: ["#C4A35A", "#3B2314"],
    description: "Vintage-style rotating globe on brass meridian stand.",
    image_url: "https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?w=600",
    dimensions: { w: 10, d: 10, h: 16 },
    assembly_required: false,
  },
  {
    id: "dc-004",
    name: "Stoneware Vase Set",
    category: "decor",
    price: 79,
    rating: 4.5,
    aesthetic_tags: ["japandi", "minimalist", "scandinavian"],
    material_tags: ["ceramic", "stone"],
    colors: ["#9C9A8E", "#D4C5A9", "#F5F0E8"],
    description: "Set of 3 matte stoneware vases in graduated sizes. Wabi-sabi glaze.",
    image_url: "https://images.unsplash.com/photo-1612198188060-c7c2a3b66eae?w=600",
    dimensions: { w: 8, d: 8, h: 12 },
    assembly_required: false,
  },
  {
    id: "dc-005",
    name: "Velvet Throw Pillows (Set of 3)",
    category: "decor",
    price: 99,
    rating: 4.4,
    aesthetic_tags: ["dark-academia", "maximalist", "bohemian"],
    material_tags: ["velvet", "cotton"],
    colors: ["#722F37", "#2D4A2D", "#C4A35A"],
    description: "Burgundy, forest green, and gold velvet cushions with piped edges.",
    image_url: "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=600",
    dimensions: { w: 18, d: 18, h: 6 },
    assembly_required: false,
  },
  {
    id: "dc-006",
    name: "Linen Throw Blanket",
    category: "decor",
    price: 69,
    rating: 4.5,
    aesthetic_tags: ["coastal-grandmother", "japandi", "scandinavian"],
    material_tags: ["linen"],
    colors: ["#7BA7BC", "#F5F0E8"],
    description: "Lightweight linen throw in faded ocean blue with fringe edges.",
    image_url: "https://images.unsplash.com/photo-1616627988170-851c60f59108?w=600",
    dimensions: { w: 50, d: 0.5, h: 60 },
    assembly_required: false,
  },
];
